[deps]
ImageEdgeDetection = "2b14c160-480b-11ea-1b58-656063328ff7"
ImageSegmentation = "80713f31-8817-5129-9cf8-209ff8fb23e1"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
IndirectArrays = "9b13fd28-a010-5f03-acff-a1bbcff69959"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
